name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest


    steps:
      - name: check out the repo
        uses: actions/checkout@v3

      - name: log in docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: zubairsource/devops-project2:latest, zubairsource/devops-project2:${{ github.run_number }}    